messenger4j:
  appSecret: 6eb0e158b93d28f649d920ef1c283594
  verifyToken : verifyabrolly
  pageAccessToken: EAAKjEkYzwlUBACzj0asIdj05eqtJaztiZBWqNAoo4GjXLvzRTOQ9TRIZB6zeZBLHhkZCMQHUSfh7b5PM8jfhsOZBt7TEryl6gKVGXQluCZAZCxhkbPC3m9LYnrTXDZCCWaO413QO2ZAg8lZBtafNAojqBzZAR4CsQ7EkZBMc7HhmniReKwZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO
